<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="NO_nb" xml:lang="NO_nb"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Karin Liang">

<title>Assignment 4, MSB104-gruppe 6, 2025</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="msb104_a4_grp6_files/libs/clipboard/clipboard.min.js"></script>
<script src="msb104_a4_grp6_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="msb104_a4_grp6_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="msb104_a4_grp6_files/libs/quarto-html/popper.min.js"></script>
<script src="msb104_a4_grp6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="msb104_a4_grp6_files/libs/quarto-html/anchor.min.js"></script>
<link href="msb104_a4_grp6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="msb104_a4_grp6_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="msb104_a4_grp6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="msb104_a4_grp6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="msb104_a4_grp6_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="msb104_a4_grp6.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 4, MSB104-gruppe 6, 2025</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Karin Liang </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="kort-sammendrag" class="level1">
<h1>Kort sammendrag</h1>
<p>Denne oppgaven undersøker regionale forskjeller i økonomisk utvikling og inntektsulikhet i Belgia, Nederland, Bulgaria og Norge ved hjelp av Eurostat-data. Analysene kombinerer tre tilnærminger: deskriptive analyser av BNP per innbygger og Gini, tverrsnittsregresjoner basert på 2017-data, samt alternative funksjonelle former og panelmodeller for perioden 2008 til 2022. Formålet er å vurdere hvordan økonomisk utvikling, utdanningsnivå, transportinfrastruktur og demografisk struktur henger sammen med regionale ulikhetsnivåer.</p>
<p>Resultatene viser at utdanningsnivå og veitetthet er de mest konsistente forklaringsfaktorene for variasjon i inntektsulikhet, mens økonomisk vekst har svak og ustabil betydning på tvers av modellene. Panelestimeringene viser svært begrenset tidsvariasjon i utdanningsnivå og demografisk struktur, noe som gjør det vanskelig å identifisere tydelige tidsdynamiske effekter i regional ulikhet. Analysene gir et oversiktsbilde av hvordan et lite sett av variabler henger sammen med regional inntektsulikhet, og kan fungere som et utgangspunkt for videre empiriske analyser og vurderinger innen regionalpolitikken.</p>
</section>
<section id="innledning" class="level1">
<h1>Innledning</h1>
<section id="bakgrunn" class="level2">
<h2 class="anchored" data-anchor-id="bakgrunn">Bakgrunn</h2>
<p>Det finnes fortsatt tydelige forskjeller i økonomisk kapasitet mellom europeiske land og mellom regioner innen hvert land. Basert på BNP per innbygger data hentet fra Eurostat kan man se at både på nasjonalt og regionalt nivå viser økonomisk utvikling betydelig variasjon, både i langsiktige trender og i tverrsnittssammenligninger. Disse forskjellene gjenspeiler ikke bare variasjoner i regional produksjonskapasitet og økonomisk struktur, men er også nært knyttet til flere nøkkelfaktorer, blant annet utdanningsnivå (høy utdanning), transportinfrastruktur (veitetthet), demografisk struktur (andel av befolkningen som er 65 år eller eldre), og nivået på eller endringen i BNP per innbygger.</p>
</section>
<section id="mål" class="level2">
<h2 class="anchored" data-anchor-id="mål">Mål</h2>
<p>Denne oppgaven integrerer analysene fra oppgave 1, 2 og 3 for systematisk å undersøke regionale forskjeller i økonomisk utvikling og forholdet mellom regional utvikling og inntektsulikhet i Belgia (BE), Nederland (NL), Bulgaria (BG) og Norge (NO). Oppgavene fokuserer på sentrale faktorer som økonomisk utvikling, utdanningsnivå, transportinfrastruktur og demografisk struktur, og analyserer hvordan disse faktorene henger sammen med regional inntektsulikhet. Videre vurderes hvor robuste disse sammenhengene er på tvers av ulike datastrukturer og metodiske rammeverk.</p>
<p>Hovedmålet i oppgave 1 er å benytte BNP og befolkningsdata fra Eurostat til å konstruere BNP per innbygger (BNPC) og Gini koeffisienten på NUTS2 nivå for perioden 2000 til 2023 for de fire landene. Dette brukes til å sammenligne nivået på regional økonomisk utvikling og de langsiktige utviklingstrendene. Gjennom en beskrivende analyse presenteres utviklingsmønstre for regionene, noe som gir et viktig bakteppe for videre analyser av regionale forskjeller og inntektsulikhet.</p>
<p>Oppgave 2 undersøker tverrsnittssammenhengen mellom regional utvikling og inntektsulikhet. Basert på tverrsnittsdata for 2017 estimeres en multiple lineær regresjonsmodell for å vurdere om økonomisk utvikling (endring i BNP per innbygger), transportinfrastruktur (veitetthet), utdanningsnivå (høy utdanning) og demografisk struktur (andel 65 år eller eldre) er systematisk forbundet med regionale nivåer av Gini koeffisienten.</p>
<p>Oppgave 3 utvider analysen metodisk ved å benytte alternative funksjonelle former, som log lineær modell, kvadratisk modell og kubisk modell, samt panelmodeller med faste effekter. Hensikten er å undersøke om de samme variablene viser robuste sammenhenger under ulike modellspecifikasjoner og i tidsdimensjonen. Paneldatastrukturen gjør det mulig å kontrollere for uobserverbare, tidsinvariante regionale egenskaper, noe som gir et mer helhetlig grunnlag for å analysere de dynamiske forholdene mellom regional utvikling og inntektsulikhet.</p>
</section>
<section id="betydning" class="level2">
<h2 class="anchored" data-anchor-id="betydning">Betydning</h2>
<p>Forholdet mellom regional utvikling og inntektsulikhet er viktig å studere fordi økonomiske forskjeller mellom regioner påvirker inntektsnivået, levekårene og de langsiktige mulighetene for befolkningen. Å identifisere hvilke faktorer som henger sammen med ulikhet, som BNP per innbygger, utdanningsnivå, veitetthet eller demografisk struktur, gir grunnlag for mer treffsikre regionale politiske tiltak.</p>
<p>Ved å kombinere langtidsdata for BNP per innbygger fra oppgave 1, tverrsnittsresultater fra oppgave 2 og alternative funksjonelle former og faste effektsmodeller fra oppgave 3, undersøker disse oppgavene om de viktigste faktorene bak regional inntektsulikhet er stabile og pålitelige. Denne helhetlige tilnærmingen gir en bredere forståelse av forholdet mellom regional utvikling og inntektsulikhet, og kan bidra med et empirisk grunnlag for videre politiske vurderinger.</p>
</section>
</section>
<section id="litteraturgjennomgang" class="level1">
<h1>Litteraturgjennomgang</h1>
<section id="tidligere-arbeid" class="level2">
<h2 class="anchored" data-anchor-id="tidligere-arbeid">Tidligere arbeid</h2>
<p>Denne delen gir en oversikt over relevant litteratur fra oppgave 1–3 og danner et faglig grunnlag for å forstå sammenhenger mellom regional utvikling, utdanning, infrastruktur, demografi og inntektsulikhet.</p>
<p><span class="citation" data-cites="LESSMANN2017110">Lessmann &amp; Seidel (<a href="#ref-LESSMANN2017110" role="doc-biblioref">2017</a>)</span> utnytter satellittdata for nattlys fra 180 land og 3166 regioner, og finner at om lag 67–70 % av landene viser sigma-konvergens, der inntektsforskjellene mellom regioner har blitt mindre over tid. Artikkelen avdekker også en N-formet sammenheng mellom økonomisk utvikling og regional ulikhet: ulikheten kan først øke, deretter avta, og igjen stige i høyinntektsfaser. Videre peker artikkelen på at utvikling, mobilitet, åpenhet, ressurser, institusjoner, overføringer og utdanning, og etnisitet utgjør syv grupper av faktorer som kan påvirke determinanter for regional ulikhet. Denne artikkelen gir et teoretisk grunnlag for disse oppgavene og viser at regional ulikhet påvirkes av flere strukturelle forhold samtidig.</p>
<p>I oppgave 1 benyttes <span class="citation" data-cites="Cappelen2009">Cappelen &amp; Mjøset (<a href="#ref-Cappelen2009" role="doc-biblioref">2009</a>)</span> til å gi ytterligere forklaringer på hvordan regionale økonomiske forskjeller oppstår. <span class="citation" data-cites="Cappelen2009">Cappelen &amp; Mjøset (<a href="#ref-Cappelen2009" role="doc-biblioref">2009</a>)</span> bruker ressursforvaltning og økonomisk utvikling i Norge, og viser at naturressurser, næringsstruktur og institusjonell utforming påvirker regioners økonomiske utviklingsmuligheter. Dette innebærer at ressursrike regioner kan ha en annen vekstbane enn andre regioner, noe som igjen påvirker regional utvikling. Videre gir <span class="citation" data-cites="su13021006">Bandeira Morais et al. (<a href="#ref-su13021006" role="doc-biblioref">2021</a>)</span> en presis introduksjon til Gini-koeffisienten, og understreker at Gini er et av de mest brukte målene for økonomisk ulikhet, der verdien går fra 0 (full likhet) til 1 (full ulikhet). Dette gir et teoretisk grunnlag for å bruke Gini-koeffisienten som hovedindikator for regional inntektsulikhet i disse oppgavene.</p>
<p>I oppgave 2 brukes utdanning, infrastruktur og demografi som sentrale forklaringsvariabler for regional ulikhet. <span class="citation" data-cites="Coady2017Income">Coady &amp; Dizioli (<a href="#ref-Coady2017Income" role="doc-biblioref">2017</a>)</span> viser at utdanningsulikhet har en positiv sammenheng med inntektsulikhet, og at økte utdanningsmuligheter kan redusere forskjeller. Dermed vil regioner med høyere utdanningsnivå ofte ha lavere ulikhet. Når det gjelder infrastruktur, finner <span class="citation" data-cites="Calderon2004Infrastructure">Calderón &amp; Servén (<a href="#ref-Calderon2004Infrastructure" role="doc-biblioref">2004</a>)</span> at forbedringer i blant annet veitetthet bidrar til økonomisk vekst og reduserer regional ulikhet, og at veitetthet typisk har en negativ sammenheng med Gini. Innen demografi viser <span class="citation" data-cites="dolls2019demographic">Dolls et al. (<a href="#ref-dolls2019demographic" role="doc-biblioref">2019</a>)</span> at aldring kan øke ulikhet, ettersom en høyere andel eldre kan bidra til større inntektsforskjeller.</p>
<p>I oppgave 3 viser <span class="citation" data-cites="kuznets2019economic">Kuznets (<a href="#ref-kuznets2019economic" role="doc-biblioref">2019</a>)</span> utviklingen i forholdet mellom økonomisk vekst og inntektsfordeling, og argumenterer for at ulikhet kan følge et mønster der den først øker, deretter stabiliserer seg og til slutt faller, med vekt på at ulikhetsnivået kan endres med økonomiske strukturer og utviklingsstadier.</p>
<p>Samlet sett bidrar disse litteraturene, gjennom perspektiver på regionale økonomiske forskjeller, målemetoder for ulikhet og faktorer som utdanning, infrastruktur og demografi, til det teoretiske utgangspunktet for disse oppgavene. Litteraturen peker gjennomgående på at ulikhet påvirkes av flere strukturelle forhold, og at disse kan variere betydelig mellom regioner. De nevnte litteraturene danner et faglig grunnlag for å analysere forholdet mellom regional utvikling og inntektsulikhet.</p>
</section>
<section id="forskningshull" class="level2">
<h2 class="anchored" data-anchor-id="forskningshull">Forskningshull</h2>
<p>Selv om eksisterende litteratur gir et viktig teoretisk grunnlag for å forstå forholdet mellom regional utvikling og inntektsulikhet, finnes det fortsatt områder som er lite utforsket.</p>
<p>For det første, på datanivå, bygger tidligere arbeid som <span class="citation" data-cites="LESSMANN2017110">Lessmann &amp; Seidel (<a href="#ref-LESSMANN2017110" role="doc-biblioref">2017</a>)</span> hovedsakelig på nasjonale eller globale sammenligninger og analyserer sammenhengen mellom utvikling og ulikhet ved hjelp av tverrnasjonale datasett. Artikkelen benytter ikke Eurostat sine harmoniserte og direkte sammenlignbare NUTS2-regiondata innenfor samme statistiske rammeverk.</p>
<p>For det andre, fokuserer mange artikler ofte på en enkelt faktor, som utdanning, infrastruktur eller demografi, og analyserer sjelden disse variablene samtidig innenfor samme empiriske ramme. I disse oppgavene analyseres imidlertid utdanningsnivå (høy utdanning), transportinfrastruktur (veitetthet), demografisk struktur (65 år eller eldre) og økonomisk utvikling (BNP per innbygger eller endringen i BNP per innbygger) samlet i en modell i forhold til regional inntektsulikhet (Gini).</p>
<p>For det tredje, bruker tidligere arbeid en enkelt analysemodell, enten tverrsnittsanalyser eller tidsseriestudier, og kombinerer sjelden flere tilnærminger som langtidsbeskrivelser, tverrsnittsregresjoner og paneldataanalyse. Dermed blir robuste tester av de samme sammenhengene på tvers av ulike metoder ofte fraværende.</p>
<p>Disse oppgavene benytter Eurostat-data og gjennomfører en sammenlignende analyse av Belgia, Bulgaria, Nederland og Norge. Gjennom langtidsbeskrivelsen av BNP per innbygger i oppgave 1, tverrsnittsanalysen i oppgave 2, og de alternative funksjonelle formene samt panelmodellene i oppgave 3, analyseres sammenhengene mellom regional økonomisk utvikling (BNP per innbygger eller endringen i BNP per innbygger), utdanning (høy utdanning), transportinfrastruktur (veitetthet), demografisk struktur (65 år eller eldre) og regional inntektsulikhet (Gini) fra flere perspektiver. På denne måten gir oppgavene en helhetlig tilnærming der de samme variablene undersøkes fra ulike metodiske vinkler, basert på én konsistent datakilde.</p>
</section>
</section>
<section id="data-og-metodikk" class="level1">
<h1>Data og metodikk</h1>
<section id="datakilder" class="level2">
<h2 class="anchored" data-anchor-id="datakilder">Datakilder</h2>
<p>Datasettet som brukes i oppgave 1 kommer fra Eurostat og inkluderer “nama_10r_3gdp” (BNP) og “demo_r_pjanaggr3” (befolkning), begge tilgjengelig på NUTS3-nivå. Basert på BNP- og befolkningsdata for perioden 2000–2023 beregnes BNP per innbygger (BNPC), og flere NUTS3-regioner slås sammen til NUTS2 ved hjelp av befolkningsvekting. Innenfor samme sammenslåingsramme beregnes også Gini-koeffisienten på NUTS2-nivå for å måle regional inntektsulikhet. Siden Eurostat kun dekker Norge fra og med 2010, er tilgjengelige år for Norge kortere enn for de andre landene i disse oppgavene. I tillegg, selv uten å slette manglende verdier, varierer antall tilgjengelige observasjoner mellom land i de opprinnelige Eurostat-datasettene, og sammenslåing etter region fører også til tap av enkelte observasjoner. Noen NUTS2-regioner består kun av en NUTS3-enhet, noe som genererer flere NA-verdier ved beregning av Gini.</p>
<p>Oppgave 2 benytter 2017-data hentet fra datasett brukt i oppgave 1, og henter i tillegg nye datasett fra Eurostat: utdanning (høy utdanning, ISCED 5–8) fra “edat_lfse_04”, demografisk struktur (andel av befolkningen som er 65 år eller eldre) fra “demo_r_pjanaggr3”, for transportinfrastruktur hentes veilengde fra “tran_r_net”, og arealdata fra “reg_area3”, som kombineres for å beregne veitetthet. Disse variablene utgjør 2017 tverrsnittsgrunnlaget for analysen av regional inntektsulikhet. Datasettene varierer i antall observasjoner mellom land, og enkelte regioner har manglende verdier, noe som fører til redusert utvalgsstørrelse etter datarensing.</p>
<p>Datasettet som brukes i oppgave 3 dekker perioden 2008–2022 og benytter de samme variablene som i oppgave 1 og oppgave 2, hentet fra de samme Eurostat-kildene. Det konstrueres analysefiler på tvers av år og modeller basert på samme datagrunnlag. Siden tilgjengelige år og datadekning varierer mellom land, får panelet en ubalansert struktur (unbalanced panel), og enkelte regioner mangler observasjoner i enkelte år. Dette reduserer antallet gyldige årsobservasjoner som kan inngå i estimeringen.</p>
</section>
<section id="metodisk-tilnærming" class="level2">
<h2 class="anchored" data-anchor-id="metodisk-tilnærming">Metodisk tilnærming</h2>
<p>Oppgave 1 benytter en beskrivende metode (beskrivende analyse) ved å beregne og sammenligne BNP per innbygger (BNPC) og Gini-koeffisienten på NUTS2-nivå for perioden 2000–2023. Dette brukes for å observere og sammenligne regional utvikling og ulikhet i Belgia, Bulgaria, Nederland og Norge. Gjennom deskriptiv statistikk og visualisering, der blant annet figurene fordeling av Gini (NUTS2) etter land og Gini per NUTS2 over tid (fasettert etter land), synliggjøres ulikhetsfordelingen mellom regioner og utviklingen over tid på en tydelig måte. Den beskrivende analysen er hensiktsmessig som et første steg før modellering, ettersom den gir en oversikt over langsiktige mønstre i regional økonomisk utvikling og identifiserer sentrale forskjeller mellom regioner.</p>
<p>Oppgave 2 bygger på tverrsnittsdata for 2017 og estimerer både en enkel lineær regresjonsmodell og en multiple lineær regresjonsmodell. I den enkle lineære regresjonsmodellen testes hovedantakelsene i OLS, inkludert linearitet, uavhengighet, homoskedastisitet, fravær av multikollinearitet og normalfordeling av residualer. Deretter inkluderes nye forklaringsvariabler i den multiple modellen, blant annet høyere utdanning, veitetthet og andelen av befolkningen som er 65 år eller eldre. Tverrsnittstilnærmingen gjør det mulig å kontrollere flere faktorer på samme tidspunkt og sammenligne ulikhetsnivåer mellom regioner, noe som gir grunnlag for å analysere statistiske sammenhenger mellom forklaringsvariabler og regional inntektsulikhet.</p>
<p>Oppgave 3 benytter paneldata for perioden 2008–2022 og inkluderer delmengdeanalyse, alternative funksjonelle former som log-lineær modell, kvadratisk modell og kubisk modell, heteroskedastisitetstesting, samt panelestimering (region FE, year FE, two-way FE og country FE). De alternative funksjonelle formene brukes for å undersøke om forholdet mellom variabler er robust under ulike modellspecifikasjoner. Deretter estimeres faste effekter (FE) for å kontrollere for region-, år- eller lands-spesifikke egenskaper som ikke varierer over tid, slik at modellen utnytter variasjon på tvers av år for å estimere sammenhengen mellom økonomisk utvikling, høyere utdanning, veitetthet og andelen av befolkningen som er 65 år eller eldre og regional inntektsulikhet (Gini). Fordelen med panel-FE-modeller er at de reduserer skjevhet fra uobserverbare faktorer og dermed gir mer robuste estimater.</p>
</section>
</section>
<section id="empiriske-funn" class="level1">
<h1>Empiriske funn</h1>
<section id="resultater-fra-oppgave-2" class="level2">
<h2 class="anchored" data-anchor-id="resultater-fra-oppgave-2">Resultater fra oppgave 2</h2>
<section id="enkel-lineær-regresjonsmodell" class="level3">
<h3 class="anchored" data-anchor-id="enkel-lineær-regresjonsmodell">Enkel lineær regresjonsmodell</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Gini_weighted ~ change_GDPC_pct, data = data_2017_a)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.06377 -0.03334 -0.01026  0.02047  0.13044 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)     0.032586   0.018641   1.748  0.09505 . 
change_GDPC_pct 0.009746   0.003353   2.906  0.00844 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04598 on 21 degrees of freedom
Multiple R-squared:  0.2869,    Adjusted R-squared:  0.2529 
F-statistic: 8.447 on 1 and 21 DF,  p-value: 0.008441</code></pre>
</div>
</div>
<p>Basert på tverrsnittsanalysen i oppgave 2 estimeres først en enkel lineær regresjonsmodell for å undersøke effekten av økonomisk utvikling (endringen i BNP per innbygger) på regional inntektsulikhet (Gini). Resultatene viser en signifikant positiv sammenheng mellom økonomisk utvikling og ulikhet. Koeffisienten for økonomisk utvikling er 0.0097 og signifikant på 1 %-nivå (p = 0.0084), noe som innebærer at regioner med høyere økonomisk vekst ofte har høyere Gini-koeffisient. Den justerte R²-verdien er 0.2529, som viser at økonomisk vekst alene har begrenset forklaringskraft for regionale ulikheter.</p>
</section>
<section id="multippel-lineær-regresjonsmodell" class="level3">
<h3 class="anchored" data-anchor-id="multippel-lineær-regresjonsmodell">Multippel lineær regresjonsmodell</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Gini_weighted ~ change_GDPC_pct + utdanning_hoy + 
    vei_tetthet + andelen_over65, data = data_2017_b)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.056288 -0.021771 -0.008074  0.018879  0.067027 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)     -0.0141580  0.1171323  -0.121  0.90521   
change_GDPC_pct  0.0112649  0.0055265   2.038  0.05738 . 
utdanning_hoy    0.0043338  0.0014869   2.915  0.00966 **
vei_tetthet     -0.0009082  0.0004069  -2.232  0.03934 * 
andelen_over65  -0.0028665  0.0043247  -0.663  0.51634   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.03782 on 17 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.5861,    Adjusted R-squared:  0.4888 
F-statistic: 6.019 on 4 and 17 DF,  p-value: 0.003313</code></pre>
</div>
</div>
<p>I den multiple lineære regresjonsmodellen inkluderes flere forklaringsvariabler, blant annet transportinfrastruktur (veitetthet), utdanning (høy utdanning) og demografisk struktur (andel av befolkningen som er 65 år eller eldre). Modellen viser en tydelig forbedring i forklaringskraft (justert R² = 0.4888), noe som indikerer at strukturelle forskjeller mellom regioner spiller en viktig rolle for regional inntektsulikhet. Resultatene viser at høy utdanning har en signifikant positiv effekt (koeffisient 0.00433, p = 0.00966), som innebærer at regioner med høyere utdanningsnivå også har større inntektsforskjeller. Veitetthet har en signifikant negativ sammenheng med ulikhet (koeffisient –0.0009, p = 0.03934), noe som viser at regioner med bedre transportinfrastruktur som regel har lavere ulikhet. Variabelen økonomisk utvikling beholder en svak positiv sammenheng i den multiple modellen (koeffisient 0.01126, p = 0.05738), men uten sterk statistisk signifikans. Andelen eldre over 65 år viser ingen signifikant effekt (p = 0.51634).</p>
<p>Samlet sett viser tverrsnittsanalysen at regional inntektsulikhet ikke kan forklares av økonomisk utvikling alene. Selv om den enkle lineære modellen indikerer en positiv sammenheng mellom økonomisk vekst og ulikhet, forklarer modellen kun om lag en fjerdedel av variasjonen mellom regioner. Den utvidede multiple modellen har derimot betydelig høyere forklaringskraft og viser at utdanningsnivå og transportinfrastruktur har de sterkeste og mest konsistente sammenhengene med ulikhet, noe som er klart sterkere enn økonomisk vekst. Sammenligningen av de to modellene viser at regional ulikhet er et resultat av flere strukturelle forhold, der utdanning og transportinfrastruktur spiller en langt viktigere rolle enn økonomisk utvikling alene.</p>
</section>
</section>
<section id="resultater-fra-oppgave-3" class="level2">
<h2 class="anchored" data-anchor-id="resultater-fra-oppgave-3">Resultater fra oppgave 3</h2>
<section id="alternative-funksjonelle-former" class="level3">
<h3 class="anchored" data-anchor-id="alternative-funksjonelle-former">Alternative funksjonelle former</h3>
<div class="cell">
<div id="tbl-funksjonsformer" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-funksjonsformer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: logaritmiske, kvadratiske, kubiske
</figcaption>
<div aria-describedby="tbl-funksjonsformer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 31%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Log-lineær modell</th>
<th>Kvadratisk modell</th>
<th>Kubisk modell</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>-0.12151</td>
<td>-0.14363</td>
<td>-0.07947</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.93697)</td>
<td>(-1.02523)</td>
<td>(-0.46799)</td>
</tr>
<tr class="odd">
<td>log(change_GDPC_pct + 1)</td>
<td>0.08266*</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(2.36393)</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>vei_tetthet</td>
<td>-0.00087*</td>
<td>-0.00086*</td>
<td>-0.00078+</td>
</tr>
<tr class="even">
<td></td>
<td>(-2.24811)</td>
<td>(-2.20387)</td>
<td>(-1.87064)</td>
</tr>
<tr class="odd">
<td>andelen_over65</td>
<td>-0.00236</td>
<td>-0.00046</td>
<td>-0.00003</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.57973)</td>
<td>(-0.10355)</td>
<td>(-0.00574)</td>
</tr>
<tr class="odd">
<td>Høy_utdanning</td>
<td>0.00467**</td>
<td>0.00475**</td>
<td>0.00450**</td>
</tr>
<tr class="even">
<td></td>
<td>(3.17124)</td>
<td>(3.26921)</td>
<td>(2.95712)</td>
</tr>
<tr class="odd">
<td>change_GDPC_pct</td>
<td></td>
<td>0.03697*</td>
<td>-0.00154</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>(2.12585)</td>
<td>(-0.02643)</td>
</tr>
<tr class="odd">
<td>I(change_GDPC_pct^2)</td>
<td></td>
<td>-0.00200</td>
<td>0.00403</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>(-1.55222)</td>
<td>(0.45855)</td>
</tr>
<tr class="odd">
<td>I(change_GDPC_pct^3)</td>
<td></td>
<td></td>
<td>-0.00028</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td>(-0.69392)</td>
</tr>
<tr class="odd">
<td>Num.Obs.</td>
<td>22</td>
<td>22</td>
<td>22</td>
</tr>
<tr class="even">
<td>R2</td>
<td>0.612</td>
<td>0.640</td>
<td>0.651</td>
</tr>
<tr class="odd">
<td>R2 Adj.</td>
<td>0.521</td>
<td>0.528</td>
<td>0.512</td>
</tr>
<tr class="even">
<td>AIC</td>
<td>-76.8</td>
<td>-76.4</td>
<td>-75.1</td>
</tr>
<tr class="odd">
<td>BIC</td>
<td>-70.2</td>
<td>-68.8</td>
<td>-66.4</td>
</tr>
<tr class="even">
<td>Log.Lik.</td>
<td>44.387</td>
<td>45.209</td>
<td>45.557</td>
</tr>
<tr class="odd">
<td>F</td>
<td>6.715</td>
<td>5.696</td>
<td>4.673</td>
</tr>
<tr class="even">
<td>RMSE</td>
<td>0.03</td>
<td>0.03</td>
<td>0.03</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="4"><ul>
<li>p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</li>
</ul></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>Her presenteres tre alternative funksjonelle former i oppgave 3: log lineær modell, kvadratisk modell og kubisk modell. Modellene estimeres med de samme kontrollvariablene som i oppgave 2, og resultatene er oppsummert i tabell <a href="#tbl-funksjonsformer" class="quarto-xref">Table&nbsp;1</a>.</p>
<p>For det første viser de tre modellene R2 verdier på henholdsvis 0.612 for log modellen, 0.640 for den kvadratiske modellen og 0.651 for den kubiske modellen. Den justerte R2 ligger i området 0.512 til 0.528, med små forskjeller mellom modellene. Når det gjelder AIC, er log modellen lavest med verdien -76.8, tett fulgt av den kvadratiske modellen med -76.4, mens den kubiske modellen er noe høyere med -75.1. Samlet sett fremstår log modellen som den beste etter modellvalgsindikatorene, mens den kvadratiske modellen har noe høyere forklaringskraft.</p>
<p>For det andre viser den log lineære modellen en koeffisient på 0.08266 for log(change_GDPC_pct + 1), som er statistisk signifikant og indikerer en positiv sammenheng mellom økonomisk utvikling og regional ulikhet. I den kvadratiske modellen er koeffisienten for change_GDPC_pct 0.03697 og fortsatt signifikant, men kvadratet av variabelen har ingen signifikant effekt. I den kubiske modellen er ingen av de tre vekstrelaterte parameterne, change_GDPC_pct, I(change_GDPC_pct^2) eller I(change_GDPC_pct^3), signifikante. Dette viser at inkludering av tredjegradsleddet ikke gir ekstra forklaringskraft, og modellen presterer svakere enn både log og kvadratisk modell.</p>
<p>For det tredje er variabelen høy_utdanning signifikant og positiv i alle tre modeller, med koeffisienter rundt 0.00475 til 0.0045. Dette viser at utdanningsnivået er den mest stabile forklaringsvariabelen i modellene. Variabelen vei_tetthet har negativ effekt i alle tre modellene og er signifikant i både log og kvadratiske modeller, med koeffisienter på henholdsvis -0.00087 og -0.00086. I den kubiske modellen er effekten svakere og kun svakt signifikant, med koeffisient -0.00078. Variabelen andelen_over65 er ikke signifikant i noen av modellspesifikasjonene.</p>
<p>Samlet sett viser tabell <a href="#tbl-funksjonsformer" class="quarto-xref">Table&nbsp;1</a> at log lineær, kvadratisk og kubisk modell alle fanger opp sammenhengen mellom økonomisk utvikling og inntektsulikhet, men med ulike resultater. Log lineær modell og kvadratisk modell viser tydeligere statistiske sammenhenger for vekstvariabelen, mens den kubiske modellen, til tross for høy R², ikke har signifikante vekstparametere og tilfører lite informasjon. Basert på sammenligning av R² og AIC vurderes log lineær og kvadratisk modell som de mest representative alternative funksjonelle formene.</p>
</section>
<section id="panelmodeller-fire-fe-spesifikasjoner" class="level3">
<h3 class="anchored" data-anchor-id="panelmodeller-fire-fe-spesifikasjoner">Panelmodeller (Fire FE-spesifikasjoner)</h3>
<div class="cell">
<div id="tbl-panel" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-panel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Sammenligning av panelmodeller
</figcaption>
<div aria-describedby="tbl-panel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Region FE</th>
<th>Year FE</th>
<th>Two-way FE</th>
<th>Country FE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Høy_utdanning</td>
<td>-0.00036</td>
<td>0.00011</td>
<td>-0.00035</td>
<td>0.00041</td>
</tr>
<tr class="even">
<td></td>
<td>(0.00044)</td>
<td>(0.00061)</td>
<td>(0.00053)</td>
<td>(0.00084)</td>
</tr>
<tr class="odd">
<td>andelen_over65</td>
<td>0.00048</td>
<td>0.00315+</td>
<td>0.00096</td>
<td>-0.00055</td>
</tr>
<tr class="even">
<td></td>
<td>(0.00088)</td>
<td>(0.00185)</td>
<td>(0.00125)</td>
<td>(0.00155)</td>
</tr>
<tr class="odd">
<td>Num.Obs.</td>
<td>204</td>
<td>204</td>
<td>204</td>
<td>35</td>
</tr>
<tr class="even">
<td>R2</td>
<td>0.004</td>
<td>0.022</td>
<td>0.006</td>
<td>0.009</td>
</tr>
<tr class="odd">
<td>R2 Adj.</td>
<td>-0.130</td>
<td>-0.028</td>
<td>-0.180</td>
<td>-0.162</td>
</tr>
<tr class="even">
<td>AIC</td>
<td>-1242.3</td>
<td>-627.2</td>
<td>-1259.9</td>
<td>-247.4</td>
</tr>
<tr class="odd">
<td>BIC</td>
<td>-1232.3</td>
<td>-617.3</td>
<td>-1249.9</td>
<td>-242.8</td>
</tr>
<tr class="even">
<td>RMSE</td>
<td>0.01</td>
<td>0.05</td>
<td>0.01</td>
<td>0.01</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td colspan="5"><ul>
<li>p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</li>
</ul></td>
</tr>
</tfoot>

</table>
</div>
</div>
</figure>
</div>
</div>
<p>For å analysere de dynamiske endringene innenfor regioner over tid estimerer oppgave 3 fire typer faste effektsmodeller: region FE, year FE, two way FE og country FE. Variabelen veitetthet er ikke inkludert i panelmodellene, siden faste effekter kun kan estimere variabler som varierer over tid innen samme region. Variabler som er tidsinvariante eller har svært liten variasjon kan ikke få identifisert koeffisienter. Derfor inneholder panelanalysen kun variablene høy_utdanning og andelen_over65, som begge varierer over tid.</p>
<p>For det første viser tabell <a href="#tbl-panel" class="quarto-xref">Table&nbsp;2</a> at alle panelmodellene har svært lave R2 verdier. Region FE har R² på 0.004, year FE 0.022, two way FE 0.006 og country FE 0.009. Den justerte R² er negativ for alle modellene i området fra -0.130 til -0.028. Dette viser at uansett hvilken type faste effekter som benyttes, har modellene svært begrenset evne til å forklare variasjonen i Gini over tid.</p>
<p>For det andre viser koeffisientenes signifikans at nesten ingen variabler er signifikante i noen av de fire modellene. Høy_utdanning ligger svært nær null i alle spesifikasjoner, med koeffisienter mellom -0.00036 og 0.00041, og ingen av dem er signifikante. Andelen_over65 viser svak signifikans i year FE modellen med koeffisient 0.00315, men er ikke signifikant i de øvrige modellene. Dette betyr at både utdanningsnivå og andelen eldre over 65 år har svært liten variasjon over tid, og selv etter kontroll for faste effekter bidrar disse variablene i liten grad til å forklare årlige endringer i Gini.</p>
<p>For det tredje viser modellsammenligningen at year FE modellen har den høyeste R² med 0.022, men forklaringskraften er fortsatt svært lav. Two way FE kontrollerer både region og år, men har likevel en R² på kun 0.006, som er lavere enn year FE. Country FE modellen bruker faste effekter på landsnivå, men inkluderer bare 35 observasjoner, og ingen av koeffisientene er signifikante.</p>
<p>Samlet sett viser tabell <a href="#tbl-panel" class="quarto-xref">Table&nbsp;2</a> at alle fire panelmodellene har svært svak forklaringskraft, og at nøkkelvariablene ikke viser signifikante effekter i tidsdimensjonen. Koeffisientene ligger nær null, og R² verdiene er gjennomgående lave. Dette viser at faste effektsmodeller ikke klarer å identifisere tydelige dynamiske endringer i regional inntektsulikhet over tid i dette datasettet.</p>
</section>
</section>
</section>
<section id="diskusjon" class="level1">
<h1>Diskusjon</h1>
<section id="viktige-innsikter" class="level2">
<h2 class="anchored" data-anchor-id="viktige-innsikter">Viktige innsikter</h2>
<p>Gjennom en komplementær analyse av tverrsnittsmodeller, alternative funksjonelle former og panelmodeller fremkommer det at regional inntektsulikhet har en kompleks og flerlagd struktur, og at ulikhet ikke bestemmes av en enkelt faktor, men av samspillet mellom flere regionale kjennetegn.</p>
<p>For det første viser den enkle lineære regresjonsmodellen en positiv sammenheng mellom økonomisk utvikling og regional ulikhet, men modellens forklaringskraft er lav med en justert R² på om lag 25 prosent. Dette viser at økonomisk vekst alene ikke er tilstrekkelig for å forklare ulikhetsnivået mellom regioner.</p>
<p>For det andre viser den multiple lineære regresjonsmodellen en betydelig økning i forklaringskraft, til rundt 49 prosent, når sentrale regionale faktorer som utdanning (høy utdanning), transportinfrastruktur (veitetthet) og demografisk struktur (andel av befolkningen som er 65 år eller eldre) inkluderes. Høy utdanning har en signifikant positiv effekt, noe som viser at utdanning er den viktigste forklaringsvariabelen. Veitetthet har en signifikant negativ effekt, noe som innebærer at regioner med bedre transportinfrastruktur har lavere inntektsulikhet. Økonomisk utvikling beholder en positiv koeffisient, men uten statistisk signifikans, noe som viser at dens forklaringsbidrag er begrenset.</p>
<p>For det tredje viser de alternative funksjonelle formene at sammenhengen mellom økonomisk utvikling og regional ulikhet varierer noe i signifikans på tvers av modellspesifikasjoner. Selv om log modellen og den kvadratiske modellen gir bedre modelltilpasning, er hovedresultatene stabilt: høy utdanning og veitetthet er signifikante i alle modeller, mens økonomisk utvikling viser svakere og mindre stabile effekter. Dette viser at utdanning og infrastruktur gir mer robuste forklaringer på ulikhet enn økonomisk vekst.</p>
<p>Til slutt viser panelmodellene at alle faste effektsmodeller har svært lav forklaringskraft. Verken country FE, year FE, region FE eller two way FE viser signifikante effekter for nøkkelvariablene over tid. Dette gjenspeiler at regional ulikhet, utdanningsnivå og befolkningsstruktur i perioden 2008 til 2022 endrer seg svært lite innen regioner, noe som gjør det vanskelig for faste effekter å identifisere tydelige tidsvariasjoner.</p>
<p>Samlet sett viser disse modellene at forskjeller i regional inntektsulikhet hovedsakelig kommer fra langsiktige forskjeller mellom regioner, særlig knyttet til utdanningsnivå og transportinfrastruktur, og ikke fra endringer over tid. Høy utdanning og veitetthet er signifikante i både tverrsnittsmodeller og de alternative funksjonelle formene, mens variablene ikke viser signifikante effekter i panelmodellene fordi de endrer seg svært lite over tid. Dette viser at regional inntektsulikhet i stor grad gjenspeiler varige forskjeller mellom regioner, og ikke variasjoner fra år til år.</p>
</section>
<section id="politiske-implikasjoner" class="level2">
<h2 class="anchored" data-anchor-id="politiske-implikasjoner">Politiske implikasjoner</h2>
<p>Resultatene fra oppgavene viser at utdanningsnivå og transportinfrastruktur er de mest konsistente faktorene knyttet til regional inntektsulikhet, mens økonomisk vekst viser svakere og mindre stabile sammenhenger. Dette gir et grunnlag for å vurdere hvilke typer tiltak som kan være mest målrettet når en ønsker å redusere regionale forskjeller.</p>
<p>For det første er utdanningsnivået konsekvent signifikant i både tverrsnittsmodellen og de alternative funksjonelle formene, og fremstår som den viktigste forklaringsvariabelen. Dette innebærer at økt tilgang til utdanning er ett av de mest effektive langsiktige virkemidlene for å redusere regional ulikhet. I regioner med svake utdanningsressurser bør politikken prioritere bedre tilgang til høyere utdanning og kompetanseheving, for å styrke regionale utviklingsmuligheter.</p>
<p>For det andre viser transportinfrastruktur, målt ved veitetthet, en tydelig negativ sammenheng med ulikhet på tvers av flere modeller. Dette tyder på at bedre regional tilknytning kan fremme balansert utvikling. For regioner med svak infrastruktur kan investeringer i transportforbindelser være et viktig virkemiddel for å redusere regionale forskjeller.</p>
<p>For det tredje er den økonomiske veksten ustabil i sin signifikans, og forklaringskraften er betydelig svakere enn for utdanning og infrastruktur. Dette betyr at økonomisk vekst alene ikke er et effektivt virkemiddel for å redusere regionale forskjeller. Regionalpolitikken bør derfor rette større oppmerksomhet mot strukturelle faktorer som utdanning og infrastruktur, i stedet for kortsiktige vekststimulerende tiltak.</p>
<p>Til slutt viser panelanalysen at de interne endringene innen regioner i perioden 2008 til 2022 er svært begrensede, og at regionale forskjeller har en tydelig langsiktig karakter. Dette innebærer at kortsiktige tiltak vanskelig kan endre ulikhetsmønstre raskt, og at politikken derfor må bygge på langsiktige og vedvarende strukturelle tiltak.</p>
<p>Med dette som bakgrunn kan politikk for å redusere regionale forskjeller med fordel prioritere tiltak som styrker utdanningsmuligheter og forbedrer transportinfrastruktur. Slike tiltak har større sannsynlighet for å gi varige forbedringer enn kortsiktige økonomiske vekststimuli.</p>
</section>
</section>
<section id="begrensninger-og-fremtidig-forskning" class="level1">
<h1>Begrensninger og fremtidig forskning</h1>
<section id="forskningsbegrensninger" class="level2">
<h2 class="anchored" data-anchor-id="forskningsbegrensninger">Forskningsbegrensninger</h2>
<p>Oppgavene har flere begrensninger knyttet til data og metode. For det første varierer Eurostats dekning mellom land, og sammenslåingen av NUTS3 til NUTS2 medfører enkelte manglende verdier, noe som reduserer antall observasjoner. Dette begrenser regresjonsmodellene og fører til en ubalansert panelstruktur, som igjen svekker muligheten til å identifisere tidsmessige endringer.</p>
<p>For det andre endrer de sentrale forklaringsvariablene seg svært lite over tid innen regionene. Dette gjelder blant annet utdanningsnivå, veitetthet og demografisk struktur. Dette gjør det vanskelig for faste effektsmodeller å identifisere deres tidsdynamiske effekter, noe som fører til generelt svak signifikans i panelanalysene.</p>
<p>For det tredje inkluderer oppgavene kun utdanningsnivå, veitetthet og demografisk struktur, ikke andre faktorer som kan påvirke regional ulikhet. På grunn av det begrensede antallet forklaringsvariabler kan modellene bare delvis belyse de faktorene som driver regional ulikhet.</p>
<p>Til slutt bygger oppgavene sine konklusjoner på statistiske sammenhenger observert i modellene, og forklaringskraften er begrenset av datadekning og modellspesifikasjoner. Mer detaljerte mekanismer mellom variablene krever videre forskning med bredere datagrunnlag og utvidede metodiske tilnærminger.</p>
</section>
</section>
<section id="konklusjon" class="level1">
<h1>Konklusjon</h1>
<section id="sammendrag" class="level2">
<h2 class="anchored" data-anchor-id="sammendrag">Sammendrag</h2>
<p>Gjennom å kombinere den langsiktige deskriptive analysen i oppgave 1, tverrsnittsregresjonsmodellen i oppgave 2 og de alternative funksjonelle formene samt panelmodellene med faste effekter i oppgave 3, undersøker de oppgavene systematisk regionale forskjeller i økonomisk utvikling og sentrale faktorer som påvirker regional inntektsulikhet i Belgia, Nederland, Bulgaria og Norge.</p>
<p>Tverrsnittsanalysen viser at høy utdanning og veitetthet har stabile og signifikante effekter på tvers av ulike modellspecifikasjoner, og er de viktigste forklaringsfaktorene for regional ulikhet. Høy utdanning har en signifikant positiv sammenheng med inntektsulikhet, noe som innebærer at regioner med en større andel høyt utdannede ofte har høyere ulikhet. Veitetthet har derimot en negativ sammenheng med ulikhet, og regioner med bedre transporttilgang har som regel lavere inntektsforskjeller. Sammenlignet med dette viser endringen i BNP per innbygger ustabile signifikansnivåer i flere modeller, noe som tyder på at økonomisk vekst ikke er den viktigste forklaringsfaktoren bak regional ulikhet.</p>
<p>Resultatene fra de alternative funksjonelle formene bekrefter dette bildet. Selv om log lineære og kvadratiske modeller gir en viss forbedring i modelltilpasning, endres verken koeffisientenes retning eller deres signifikans på en vesentlig måte. Effekten av høy utdanning og veitetthet forblir robust, mens økonomisk vekst fortsatt har begrenset forklaringskraft.</p>
<p>Panelmodellene viser at de sentrale variablene har svært begrenset tidsvariasjon innen regionene i perioden 2008 til 2022. Høy utdanning og den demografiske strukturen (andel 65 år eller eldre) fremstår uten signifikante effekter i faste effektsmodeller. Dette indikerer at regional inntektsulikhet i større grad gjenspeiler vedvarende forskjeller mellom regioner enn kortsiktige årlige endringer.</p>
<p>Samlet sett viser modellresultatene at tiltak for å redusere regionale inntektsforskjeller bør legge større vekt på langsiktige innsatsområder som å øke utdanningsnivå og forbedre transportinfrastruktur, i stedet for å støtte seg på kortsiktige tiltak for å stimulere økonomisk vekst.</p>
<p>Betydningen av disse funnene er at de bidrar til å identifisere hvilke faktorer som har sterkest sammenheng med regional ulikhet, noe som kan hjelpe beslutningstakere med å målrette innsatsen mer effektivt.</p>
</section>
<section id="sluttrefleksjon" class="level2">
<h2 class="anchored" data-anchor-id="sluttrefleksjon">Sluttrefleksjon</h2>
<p>Basert på de ulike datastrukturene og metodiske tilnærmingene som oppgave 1, 2 og 3 benytter, har forholdet mellom regional utvikling og inntektsulikhet kunnet undersøkes fra flere perspektiver. Ved å kombinere deskriptive analyser, tverrsnittsmodeller og panelestimeringer har oppgavene vist hvordan valg av metode og datagrunnlag påvirker de empiriske resultatene, og understreket betydningen av å bruke flere metodiske tilnærminger i regional forskning.</p>
<p>Utfordringer knyttet til datadekning på tvers av land, manglende observasjoner og begrenset tidsvariasjon i sentrale variabler gjenspeiler også praktiske begrensninger som ofte oppstår i analyser av regionale data. Til tross for disse utfordringene viser resultatene på tvers av modellene en viss konsistens, noe som gjør det mulig å identifisere utdanningsnivå og transportinfrastruktur som de mest sentrale faktorene knyttet til regionale forskjeller.</p>
<p>Analysene gir et mer konkret bilde av hvordan et lite sett av variabler kan være knyttet til regional inntektsulikhet. Selv om analysene ikke kan si noe om årsakssammenhenger, gir arbeidet nyttige erfaringer med bruk av ulike metoder, noe som kan være relevant for videre empiriske studier på området.</p>
</section>
</section>
<section id="vedlegg-bruken-av-ai-verktøy" class="level1">
<h1>Vedlegg-Bruken av AI-verktøy</h1>
<p>Jeg benyttet ChatGPT (modell GPT-5.1) i arbeidet med MSB104 oppgave 4, hovedsakelig som støtte til oversettelse mellom kinesisk og norsk. Basert på mine egne kinesiske utkast brukte jeg ChatGPT til å oversette innholdet til norsk og til å få forslag til mer naturlige eller mer akademiske formuleringer. Jeg gjennomgikk alle forslagene og teksten som ble generert av ChatGPT, redigerte og omorganiserte dem for å sikre at terminologien, strukturen og det analytiske rammeverket var i samsvar med det opprinnelige utkastet. Gjennom hele prosessen bidro ChatGPT til å forbedre sammenheng og språklig klarhet i tekstene. Alle formuleringer ble kontrollert av meg setning for setning, og jeg sørget for at de var i tråd med min egen analyse og forståelse.</p>
</section>
<section id="referanser" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referanser</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-su13021006" class="csl-entry" role="listitem">
Bandeira Morais, M., Swart, J., &amp; Jordaan, J. A. (2021). Economic complexity and inequality: Does regional productive structure affect income inequality in brazilian states? <em>Sustainability</em>, <em>13</em>(2). <a href="https://doi.org/10.3390/su13021006">https://doi.org/10.3390/su13021006</a>
</div>
<div id="ref-Calderon2004Infrastructure" class="csl-entry" role="listitem">
Calderón, C., &amp; Servén, L. (2004). <em>The effects of infrastructure development on growth and income distribution</em> (Policy Research Working Paper No. 3400). World Bank. <a href="https://hdl.handle.net/10986/14136">https://hdl.handle.net/10986/14136</a>
</div>
<div id="ref-Cappelen2009" class="csl-entry" role="listitem">
Cappelen, Ø., &amp; Mjøset, L. (2009). Can norway be a role model for natural resource abundant countries? <em>Discussion Papers in Economics</em>, <em>09</em>, 1–26. <a href="https://www.researchgate.net/publication/228983025_Can_Norway_Be_a_Role_Model_for_Natural_Resource_Abundant_Countries">https://www.researchgate.net/publication/228983025_Can_Norway_Be_a_Role_Model_for_Natural_Resource_Abundant_Countries</a>
</div>
<div id="ref-Coady2017Income" class="csl-entry" role="listitem">
Coady, D., &amp; Dizioli, A. (2017). Income <span>Inequality</span> and <span>Education</span> <span>Revisited</span>: Persistence, <span>Endogeneity</span>, and <span>Heterogeneity</span>. <em>IMF Working Papers</em>, <em>17</em>(126), 1. <a href="https://doi.org/10.5089/9781475595741.001">https://doi.org/10.5089/9781475595741.001</a>
</div>
<div id="ref-dolls2019demographic" class="csl-entry" role="listitem">
Dolls, M., Doorley, K., Paulus, A., Schneider, H., &amp; Sommer, E. (2019). Demographic change and the european income distribution. <em>The Journal of Economic Inequality</em>, <em>17</em>(3), 337–357.
</div>
<div id="ref-kuznets2019economic" class="csl-entry" role="listitem">
Kuznets, S. (2019). Economic growth and income inequality. In <em>The gap between rich and poor</em> (pp. 25–37). Routledge.
</div>
<div id="ref-LESSMANN2017110" class="csl-entry" role="listitem">
Lessmann, C., &amp; Seidel, A. (2017). Regional inequality, convergence, and its determinants – a view from outer space. <em>European Economic Review</em>, <em>92</em>, 110–132. https://doi.org/<a href="https://doi.org/10.1016/j.euroecorev.2016.11.009">https://doi.org/10.1016/j.euroecorev.2016.11.009</a>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>